Controllers/FacebookLoginController.cs
using DemoApplication1.Models.DataAccess;
using DemoApplication1.Models.Entities.Concretes;
using DemoApplication1.Models.Services.Abstracts;
using DemoApplication1.Models.SingletonServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace DemoApplication1.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class FacebookLoginController : Controller
    {
      
        private readonly IAccessTokenDal _accessTokenDal;
        private readonly ILoginService _loginService;

        public FacebookLoginController(IAccessTokenDal accessTokenDal,ILoginService loginService)
        {
            _accessTokenDal = accessTokenDal;
            _loginService = loginService;
        }


        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.userId = SessionSingleton.GetInstance()._session.GetString("userId");
            return View("Login");
        }

        [HttpPost]
        [Route("AddAccessTokenInfoToDb")]
        public string AddAccessTokenInfoToDb(AccessTokenData accessTokenData)
        {
            var tokenData= _loginService.MakeAccessTokenLongLife(accessTokenData.AccessToken);
            accessTokenData.AccessToken = tokenData.AccessToken.ToString();
            accessTokenData.ExpiresIn = tokenData.ExpiresIn.ToString();
            _accessTokenDal.SaveAccessToken(accessTokenData);
            return accessTokenData.AccessToken;

        }

       
    }
}

Controllers/LoginController.cs
using DemoApplication1.Models.Entities.Concretes;
using DemoApplication1.Models.Services.Abstracts;
using DemoApplication1.Models.SingletonServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace DemoApplication1.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class LoginController: Controller {

        private readonly ILoginService _loginService;

        public LoginController(ILoginService loginService)
        {
            _loginService = loginService;
        }

       

       

        [HttpGet]
        [Route("Login")]
        public bool Login(string username,string password) {

           var userId= _loginService.Login(username,password);

            if (userId!=null)
            {
                string val = userId.ToString();
                SessionSingleton.GetInstance()._session.SetString("userId", val);
                return true;
            }
            return false;
        }

        
       
        [HttpGet]
        [Route("CheckUserAccessToken")]
        public bool CheckUserAccessToken()
        {
            string idVal = SessionSingleton.GetInstance()._session.GetString("userId");
            if (idVal != null)
            {
                int id = int.Parse(idVal);
                bool result = _loginService.CheckUserAccessToken(id);
                return result;
            }
            return false;
        }

       
        [HttpGet]
        [Route("IsAccessTokenActive")]
        public bool IsAccessTokenActive()
        {
            string idVal = SessionSingleton.GetInstance()._session.GetString("userId");
            if (idVal != null)
            {
                int id = int.Parse(idVal);
                bool result = _loginService.IsAccessTokenActive(id);
                return result;

            }
            return false;
        }


        
        [HttpPost]
        [Route("Register")]
        public void Register(User user)
        {
            _loginService.Register(user);

        }

        
        [HttpGet]
        [Route("GetAccessToken")]
        public string GetAccessToken()
        {
    
            return _loginService.GetToken(int.Parse(SessionSingleton.GetInstance()._session.GetString("userId")));

        }

    }
}

Views/FacebookLogin/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>

    <h1 id="hh">Hello Silence !!!</h1>
    <fb:login-button scope="public_profile,email"
                     onlogin="checkLoginState();">
    </fb:login-button>
    <div id="authStatus"></div>

    <script>

        var user = { userId: "", accessToken: "" , expiresIn: "" , dataAccessExpirationTime: "" , isActive: "" , foreignKeyId: "" };

        window.fbAsyncInit = function () {

            FB.init({
                appId: '881418686127166',
                cookie: true,
                xfbml: true,
                version: 'v11.0'
            });

            FB.AppEvents.logPageView();

        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

        var val1 = '@ViewBag.userId';
        
        //url: 'Url.Action("AddAccessTokenInfoToDb", " FacebookLogin")',

        function checkLoginState() {
            FB.getLoginStatus(function (response) {
            $("#authStatus").html("<code>" + JSON.stringify(response, null, 2) + "</code>")
                if (response.status === 'connected') {
                    user.userId = response.authResponse.userID;
                    user.accessToken = response.authResponse.accessToken;
                    user.expiresIn = response.authResponse.expiresIn;
                    user.dataAccessExpirationTime = response.authResponse.data_access_expiration_time;
                    user.isActive ="active";
                    user.foreignKeyId =val1;

                     //url: "https ://localhost:44325/FacebookLogin/AddAccessTokenInfoToDb ",
                    console.log(user);

                    $.ajax({
                            url: '@Url.Action("AddAccessTokenInfoToDb", "FacebookLogin")',
                            dataType: 'json',
                            method: "POST",
                            data: JSON.stringify(user),
                         contentType: 'application/json; charset=UTF-8',

                    });

                }
                    //window.location.replace("https://localhost:44325/FacebookLogin?info=" + response.authResponse.accessToken);

            });
        }


    </script>

</body>

</html>